- name: Install dependencies
  apt:
    name:
      - build-essential
      - zlib1g-dev
      - libssl-dev
      - libreadline-dev
      - libyaml-dev
      - libcurl4-openssl-dev
      - libffi-dev
      - libpq-dev

- name: Install httpd
  apt:
    name: 
      - apache2
      - apache2-dev

- name: Install passenger
  gem:
    name: passenger
    executable: "{{gem_path}}"
    user_install: no

- name: Install passenger apache2 module
  shell: $0 -lc "passenger-install-apache2-module --auto --languages ruby"
  args:
    creates: /etc/apache2/conf-available/redmine.conf

- name: Get passenger apache2 module snippet
  shell: $0 -lc "passenger-install-apache2-module --snippet"
  register: passenger_snippet

- name: Add redmine.conf
  template:
    src: redmine.conf.j2
    dest: /etc/apache2/conf-available/redmine.conf

- name: Enable redmine.conf
  shell: a2enconf redmine

- name: Change DocumentRoot
  lineinfile:
    state: present
    dest: /etc/apache2/sites-enabled/000-default.conf
    regexp: 'DocumentRoot'
    line: DocumentRoot /var/lib/redmine/public
    backup: yes

- name: Change owner
  shell: chown -R www-data:www-data /var/lib/redmine/

- name: Restart httpd
  service:
    name: apache2
    state: restarted
    enabled: yes
