- name: Clone rbenv
  git:
    repo: "{{rbenv_repo}}"
    dest: "{{rbenv_root_dir}}"

- name: Create rbenv plugins directory
  file:
    dest: "{{rbenv_root_dir}}/plugins"
    state: directory

- name: Clone ruby-build
  git:
    repo: "{{rbenv_ruby_build_repo}}"
    dest: "{{rbenv_root_dir}}/plugins/ruby-build"

- name: Add configuration
  template:
    src: rbenv.sh.j2
    dest: /etc/profile.d/rbenv.sh

- name: Install dependencies
  yum:
    name: 
      - bzip2
      - gcc
      - openssl-devel
      - readline-devel
      - zlib-devel

- name: Install ruby
  shell: $0 -lc "rbenv install --skip-existing {{ruby_version}}"

- name: Set global ruby
  shell: $0 -lc "rbenv global {{ruby_version}}"
